### ISSUE TITLE
Polymer Tutorial does not work with gwt-2.7.0 (webAppCreator broken)

### ISSUE THREAD

**Issue by florian-f** [gwtproject/gwt-site#114]
Currently, the [Polymer Tutorial](http://www.gwtproject.org/doc/latest/polymer-tutorial/create.html) doesn't work.

Due to this issue: https://github.com/gwtproject/gwt/issues/9006  the project created in 'Creating the TodoList Project' won't compile. The status of that issue is FixedNotReleased, so maybe for now we should just tell the reader about this and mention how to fix the problem:
>   - workarounds:
>     * create the project using webappcreator from 2.6.1 and change versions
>     * or add versions to gwt dependencies.

I guess that another workaround is to use the latest webAppCreator from trunk but I haven't veryfied that yet. Also, I don't think that everyone who reads the tutorial would want to build gwt first.

**Comment by florian-f** [comment]
ok so even after adding versions to the gwt dependencies the pom.xml still has some issues. 
I got it to work by using parts of the pom.xml of the demo in gwt-polymer-elements https://github.com/vaadin/gwt-polymer-elements/blob/master/demo/pom.xml

**Comment by manolo** [comment]
The only thing to do after using webAppCreator from 2.7.0 to make it compile is to add the field `type` 

```
<dependencyManagement>
    <dependencies>
      <!-- ensure all GWT deps use the same version (unless overridden) -->
      <dependency>
        <groupId>com.google.gwt</groupId>
        <artifactId>gwt</artifactId>
        <version>${gwtVersion}</version>
        <scope>import</scope>
        <type>pom</type>
      </dependency>
    </dependencies>
  </dependencyManagement>
```

Also the webAppCreator does not copy the static stuff in `webapp` unless you run `mvn package`
BTW, `pom.xml` in demo has not been created with `webappCreator`. 

I'll update the tutorial with these tips.
