### ISSUE TITLE
Is it possible to provide a ziped doc pakeage of old version for downloading?

### ISSUE THREAD

**Issue by AlexLuya** [gwtproject/gwt-site#138]
Hello,www.gwtproject.com is blocked here and VPN is very unstable,these cause a real problem for new members of our team to learn gwt.Is it possible to provide a ziped doc pakeage of old version for downloading if new version isn't possible?

**Comment by tbroyer** [comment]
1. `git clone https://github.com/gwtproject/gwt-site.git` (hopefully not blocked)
2. `mvn verify` (see the README for details about building the project)
3. `mvn jetty:run` (or zip/deploy/whatever the `target/generated-site` directory)
