### ISSUE TITLE
"If you find errors, please report them or change them!" tries to point to #webpage but does not

### ISSUE THREAD

**Issue by Splaktar** [gwtproject/gwt-site#15]
This line has been here for quite a while:
https://github.com/gwtproject/gwt-site/blob/e3ecf4332cd23a9e5a6d9b439326a8f9e5ba842c/src/main/resources/main.tpl#L64

But the `#webpage` piece of `<a href="makinggwtbetter.html#webpage">` doesn't seen to work in production as that links to http://www.gwtproject.org/makinggwtbetter.html

The template processor seems to be pulling out the #webpage resulting in `<a href="/makinggwtbetter.html">change them</a>`

**Comment by jDramaix** [comment]
Thanks we will fix that very soon!

**Comment by jDramaix** [comment]
I think we can close it now :-)
