### ISSUE TITLE
MVP Activities and Places: Bad link to hellomvp source code

### ISSUE THREAD

**Issue by murraycu** [gwtproject/gwt-site#170]
This page:
http://www.gwtproject.org/doc/latest/DevGuideMvpActivitiesAndPlaces.html
has a "this sample app" link to here:
http://code.google.com/p/google-web-toolkit/downloads/detail?name=Tutorial-hellomvp-2.1.zip

But that code.google.com site is now old and archived and presumably should not be used any more at all. There is a Tutorial-hellomvp .zip download on the second page in that list of downloads, but the link suggests that it should be easier to find. Anyway, the source code should be in git.

**Comment by haridaniel** [comment]
The new url: https://storage.googleapis.com/google-code-archive-downloads/v2/code.google.com/google-web-toolkit/Tutorial-hellomvp-2.1.zip
