### ISSUE TITLE
StockWatcher HTML has error

### ISSUE THREAD

**Issue by 148349** [gwtproject/gwt-site#179]
http://www.gwtproject.org/doc/latest/tutorial/buildui.html has errorneous code for the StockWatcher.html file.

The line`<script type="text/javascript" language="javascript" src="stockwatcher/stockwatcher.nocache.js"></script>`

should be:
`<script type="text/javascript" language="javascript" src="StockWatcher/StockWatcher.nocache.js"></script>`

**Comment by happyhua** [comment]
Check your StockWatcher.gwt.xml file.

Normally you will see: &lt;module rename-to='**stockwatcher**'>

Probably in your case you have StockWatcher.

**Comment by tbroyer** [comment]
http://www.gwtproject.org/doc/latest/tutorial/create.html#components has `rename-to="stockwatcher"`, and `webAppCreator` will use lowercase: https://github.com/gwtproject/gwt/blob/2.7.0/user/src/com/google/gwt/user/tools/WebAppCreator.java#L617 & https://github.com/gwtproject/gwt/blob/2.7.0/user/src/com/google/gwt/user/tools/templates/sample/_srcFolder_/_moduleFolder_/_moduleShortName_.gwt.xmlsrc#L2

So I agree the documentation is OK. Thanks @happyhua for the heads up.
