### ISSUE TITLE
Missing Older Versions

### ISSUE THREAD

**Issue by Kasper34** [gwtproject/gwt-site#196]
I went to http://www.gwtproject.org/versions.html and attempted to download version 2.3.0 and was greeting with:
1. That’s an error.
   The requested URL /files/gwt-2.3.0.zip was not found on this server. That’s all we know.

The resource was not found at this location:
http://google-web-toolkit.googlecode.com/files/gwt-2.3.0.zip

Version 2.6.0 and below are also not found.

**Comment by tbroyer** [comment]
If you really need them, old downloads have been archived at https://code.google.com/archive/p/google-web-toolkit/downloads

Maybe you could make a pull-request updating the links to the new archived location?

**Comment by wlsc** [comment]
Opened PR for this at https://github.com/gwtproject/gwt-site/pull/205
