### ISSUE TITLE
Site Not Available Over Https

### ISSUE THREAD

**Issue by vidalborromeo** [gwtproject/gwt-site#210]
(eom)

**Comment by tbroyer** [comment]
Looks like we can have it now: https://cloudplatform.googleblog.com/2017/09/introducing-managed-SSL-for-Google-App-Engine.html

**Comment by TDesjardins** [comment]
Release of GWT 2.9.0 would be a good time to finally solve this issue. A dev site without SSL doesn't look very reputable in 2020.

**Comment by niloc132** [comment]
This has been resolved at last, we've migrated away from GCE and it is now possible for this to be enabled. From the announcement at https://groups.google.com/g/google-web-toolkit-contributors/c/zzP37WaWOtU/m/jAVOOHkuBgAJ, there are a few small changes from the old hosting 

> * HTTPS is now supported and enabled, though not yet mandatory, to allow a period of migration, and making sure that no downstream tools will break as a result of these changes. HSTS is also disabled for now. I propose that mid-week I will update this to always redirect to HTTPS, and then in another two or three weeks consider enabling HSTS if there have been no reported issues.
> * The [samples.gwtproject.org](http://samples.gwtproject.org/) domain now redirects to the showcase, rather than giving a confusing 500 error. The samples are still at this time hosted as static content rather than servlets.
> * The GWT application that enhances the documentation has been updated, picking up changes published ~2 years ago.
> * Deep links that omit "www." (for example [gwtproject.org/doc/latest/DevGuide.html](http://gwtproject.org/doc/latest/DevGuide.html)) will now redirect to the expected page (in this case [www.gwtproject.org/doc/latest/DevGuide.html](http://www.gwtproject.org/doc/latest/DevGuide.html)) rather than redirecting only to [www.gwtproject.org](http://www.gwtproject.org/).
