### ISSUE TITLE
Issues with the official Website

### ISSUE THREAD

**Issue by thakurpunk** [gwtproject/gwt-site#224]
Hello There,

I was browsing through your official website and found some bugs, please refer to the screenshot attached.

![screenshot_1](https://cloud.githubusercontent.com/assets/8851526/23519082/aeaa3a48-ff9b-11e6-9ea9-8393f3a900dd.png)

Thank you!

**Comment by tbroyer** [comment]
Hmm, I confirm the strange content (Chrome on Ubuntu 16.10) and broken behavior.

![image](https://cloud.githubusercontent.com/assets/173813/23519703/2ed559f6-ff78-11e6-9ad6-98ce2ec11fc4.png)

**Comment by thakurpunk** [comment]
@tbroyer the content have unwanted characters, even this is not a technical issue. lol

**Comment by tbroyer** [comment]
Yup, those are ETX (0x03) characters: https://en.wikipedia.org/wiki/End-of-Text_character and are there for 3 years. I suppose the reason they only show up now (for me, only in Chrome, not in Firefox; can't reproduce in Edge either in a Win10 VM) is that Chrome recently changed the way they handle them (confirmed in my Win10 VM: Chrome 55 doesn't display them, updated to 56 and they now appear).
