### ISSUE TITLE
What is the right way to include javascript libraries (multiple files) in your app?

### ISSUE THREAD

**Issue by dmg46664** [gwtproject/gwt-site#230]
I can see the following pages:
http://www.gwtproject.org/doc/latest/DevGuideOrganizingProjects.html#DevGuideModules
However, they all seem to refer to single file inclusions.

http://www.gwtproject.org/doc/latest/DevGuideOrganizingProjects.html#DevGuidePathFiltering
The filtering and filesets section sounds like it might be relevant... but probably this is referring to Java files, not javascript files. Although perhaps `<public>` is what I want?

http://www.gwtproject.org/doc/latest/DevGuideOrganizingProjects.html#DevGuideModuleXml (XML element reference).
More on `<public>` here.

There is also [this google groups discussion](https://groups.google.com/forum/#!topic/google-web-toolkit/Xiz8XmPhJzo) which suggests to use `ScriptInjector` and although the reasons seem antiquated, perhaps this is still the right approach for this scenario?

My use case is to embed [Ace](https://ace.c9.io/#nav=embedding) and although there is a wrapper GWT project already, I'd prefer to use a `JsInterop` approach.

I don't see easy documentation to help make a decision on the best mechanism. My criteria is essentially:
1. Include multiple javascript files in multiple directories.
1. Not have to include them by hand one at a time.
1. Optimize the javascript files (preferably merging them into the payload).

I thought I'd write this up here first, as I figured it's most likely a documentation issue.
TIA.

**Comment by dmg46664** [comment]
Will probably end up writing a shell script to compile the list 😖 😄

**Comment by dmg46664** [comment]
Solution was to:
- Add a second module in my `resources` folder
- Add a `public` directory under that.
- Put all the app files there.

Took a queue from https://github.com/vaadin/gwt-polymer-elements
(Although first thought that it was using `<source>` to do the inclusion as public is explicit).

I think the documentation could be improved to specifically mention javascript as a public resource. I'd imagine that it might be handled differently to images and css.

**Comment by jnehlmeier** [comment]
It depends on what you want to achieve.

Files in the public folder are simply copied to the GWT compiler output directory. How you finally use them in your app is up to you. You either have to add static <script> tags in your host html page or add them dynamically through code.

If you use <script> in your GWT module, then GWT will install the scripts in your host page and make sure they are loaded before the GWT app loads, but I believe it is only useful for GWTTestCase these days. No idea, actually never used that approach. I think it is also incompatible to the current default linker used by GWT.

If you use ClientBundle + (multiple) TextResource + ScriptInjector the JS code can be embedded into your app code if you want that. Alternatively you could put it behind a GWT split point and only download it when needed (for example a charting library). That is what I usually use.

Sadly in all cases GWT does not optimize the JS of the external scripts (e.g. no code pruning of features you do not use).

**Comment by Lenkabelakova** [comment]
Will probably end up writing a shell script to compile the list 😖 😄

**Comment by manolo** [comment]
Apart from the text resources which does not reduces or checks your javascript, there is a `JsniBundle` in gwtquery able to get a external javascript and include it in a jsni block so as it's delivered in your compilation unit, and also it's is minimized my the gwt compiler.

In gwtproject.org we are using it for the syntax coloring library, take a look to this folder

https://gwt.googlesource.com/gwt-site-webapp/+/master/src/main/java/com/google/gwt/site/webapp/client/highlight/ 

Also for an explanation of how to use it take a look to

http://stackoverflow.com/questions/20164434/injecting-jquery-through-scriptinjector/20172975#20172975
