### ISSUE TITLE
Google+ is no longer available, remove the link

### ISSUE THREAD

**Issue by nbartels** [gwtproject/gwt-site#288]
Because google+ is dead, you should remove the link to the community and replace it with the new community link, if there is some.

https://github.com/gwtproject/gwt-site/blob/cb0257f01c3be07bb050aa76440f12fcbe8f57ab/src/main/site/index.html#L73

**Comment by TDesjardins** [comment]
There are several other locations where g+ is linked. I would prefer to replace it with a link to the gitter room: https://gitter.im/gwtproject/gwt-modules
