### ISSUE TITLE
gwt 2.9.0 release notes update

### ISSUE THREAD

**Issue by chenrui333** [gwtproject/gwt-site#298]
v2.9.0 was released on May 1, but the latest release on the http://www.gwtproject.org/release-notes.html is still with v2.8.2.

**Comment by niloc132** [comment]
I'm not sure where you got that impression - gwt 2.9.0 has not been released yet. If you are referencing a zip, it is a pre-release still undergoing testing, and is not ready to be used until we officially announce it. 

The zip link referenced in your linked issue is the location where the candidate that is under release will go. Depending on when you download from a link like that, you may or may not get the final release, if we haven't finished testing.

https://search.maven.org/artifact/com.google.gwt/gwt shows that there is no 2.9.0 officially released in maven central.

--

All of that being said, yes barring something terrible happening, that will be the final release (hopefully today, in fact), but until it is released officially, it isn't released ;).

**Comment by niloc132** [comment]
Release did go out last night, but the deploy process for the site failed! The release zip you have at that link is official, as are the maven artifacts, we'll get the site hopefully updated today.

Closing this, i'll remark on the other issue too.

**Comment by chenrui333** [comment]
perfect, will keep an eye on this, thanks for the update.
