### ISSUE TITLE
Sidebar broken

### ISSUE THREAD

**Issue by eric-create** [gwtproject/gwt-site#373]
Hi there,

it seems that the sidebar is broken since yesterday. Once you've entered https://www.gwtproject.org/ and clicked on e.g. "Tutorials" the sidebar collapses and stays collapsed forever. I am pretty sure this was different before today (I visited the site mon/tue and last week thur). Also it seems not to be possible to get back to https://www.gwtproject.org/ using any button.

**Comment by FrankHossfeld** [comment]
Please check this:

Click on tutorial and move the mouse arrow to the right. Does this work?

**Comment by eric-create** [comment]
I am trying that on macos and Edge and it won't work

**Comment by FrankHossfeld** [comment]
Mmmh, can not see the problem:

https://github.com/user-attachments/assets/141bfc69-46be-4ef6-b40e-af466644101b

macOS using Edge

**Comment by eric-create** [comment]
Oh must be some kind of cookie thing - couldn't identify the one yet though. However in private browser window it works as expected.
