### ISSUE TITLE
Feedback From HN Users, Landing Page

### ISSUE THREAD

**Issue by florian-f** [gwtproject/gwt-site#38]
https://news.ycombinator.com/item?id=8945858

tl;dr
people seem to think the landing page doesn't explain well what gwt is about.

[proposed solution (by a member of the gwt g+ group):](https://plus.google.com/111111256905510835953/posts/JATJER2Le4E)

> the idea of "develop your app in Java, deploy to HTML+JavaScript", should be up front;

**Comment by tbroyer** [comment]
:+1:

The mission statement should be moved/copied from http://www.gwtproject.org/makinggwtbetter.html to the front page.
