### ISSUE TITLE
Scrolling buttons do not function properly in Safari and Chrome.

### ISSUE THREAD

**Issue by mehrdadrafiee** [gwtproject/gwt-site#50]
As you can see, I opened the page in Safari and Google Chrome and pushed the middle and the higher scrolling buttons (right side of the page), but it is not scrolling to the top of the page. Actually, none of the scrolling buttons work properly.

Please see the attachment for more details.

![screen shot 2015-02-19 at 12 35 07 am](https://cloud.githubusercontent.com/assets/7308807/6263661/7dc94042-b7cf-11e4-9947-c5509cea7d30.png)
![screen shot 2015-02-19 at 12 36 26 am](https://cloud.githubusercontent.com/assets/7308807/6263662/7de7902e-b7cf-11e4-9516-698ca6be24bf.png)

**Comment by jDramaix** [comment]
Thanks this is a known problem: see #18
