### ISSUE TITLE
Reword "quickly develop performance AJAX applications" sentence on home page

### ISSUE THREAD

**Issue by qtrandev** [gwtproject/gwt-site#53]
On the project home page at http://www.gwtproject.org, this sentence may need to be reworded: "how you can quickly develop performance AJAX applications across all major browsers" - it may be changed to "high-performance". This file is at src/main/markdown/index.md.

**Comment by jDramaix** [comment]
Could you propose a pull request for this ?

**Comment by qtrandev** [comment]
Created pull request #54

**Comment by jDramaix** [comment]
Thanks
