### ISSUE TITLE
Old look after getting repo and running locally

### ISSUE THREAD

**Issue by okrasz** [gwtproject/gwt-site#56]
I've cloned the repository and run the `mvn clean install` and `mvn jetty:run`. After opening it in browser it appeared with the old layout.

**Comment by jDramaix** [comment]
you have to use the `gwt-new-site` branch

**Comment by okrasz** [comment]
Thanks. So, wouldn't it make sense to change the branch to be master as this is current version of the site? I guess it would be more intuitive for new comers.

**Comment by jDramaix** [comment]
The branch will be merged into master soon
