### ISSUE TITLE
Where is the webapp?

### ISSUE THREAD

**Issue by akkinenirajesh** [gwtproject/gwt-site#68]
This project depends on webapp which is a gwt project.
GWTProjectEntryPoint.java and its corresponding folders are missing in this project?

Can some one point me to where they are available?

**Comment by tbroyer** [comment]
Sure: https://gwt.googlesource.com/gwt-site-webapp/

Contributions go through Gerrit, like for GWT itself.

**Comment by branflake2267** [comment]
Just a thought, since it isn't an API and doesn't need high scrutiny, might be nifty if it was moved. :)
